# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_news', '0003_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='300x250px', upload_to='images/blog/%Y/%m/%d', verbose_name='url img'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default='2017-12-06 12:16:44.212924'),
        ),
    ]
